# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=line-too-long
# pylint: disable=too-many-lines

from knack.help_files import helps  # pylint: disable=unused-import


helps['change-safety change-state create'] = """
    type: command
    short-summary: Create a change state record.
    parameters:
      - name: --targets
        short-summary: Target definitions impacted by this change. Provide space-separated arguments, each containing one or more key=value pairs separated by ' ,' or ' ;'.
"""

helps['change-safety change-state update'] = """
    type: command
    short-summary: Update a change state record.
    parameters:
      - name: --targets
        short-summary: Replace the target definitions for this change. Provide key=value pairs separated by commas or semicolons within each argument.
"""
